steps:
  # Pull previous image for caching
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/autofinance-bot:latest || exit 0']
  
  # Build with cache
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'cloud'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/autofinance-bot:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/autofinance-bot:latest',
      '.'
    ]
  
  # Push to registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/autofinance-bot:latest']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'autofinance-bot',
      '--image', 'gcr.io/$PROJECT_ID/autofinance-bot:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '4Gi',
      '--cpu', '2',
      '--timeout', '600',
      '--max-instances', '10',
      '--set-env-vars',
      'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},ANTHROPIC_API_KEY=${_ANTHROPIC_API_KEY},OPENAI_API_KEY=${_OPENAI_API_KEY},BOT_MODEL=${_BOT_MODEL}'
    ]

images:
  - 'gcr.io/$PROJECT_ID/autofinance-bot:latest'

options:
  machineType: 'E2_HIGHCPU_8'  # 8x faster builds (~$0.16 per build vs free)
